### ISSUE TITLE
Search cmd

### ISSUE THREAD

**Issue by Lamby777** [IIIzP0III/Back-at-Home#6]
Gonna work on this in a bit

- [x] Search homes `/homes search asdfjkl;`
- [x] Paginate list

**Comment by Lamby777** [comment]
[wenomechainsama](https://github.com/xdrop/fuzzywuzzy)

**Comment by IIIzP0III** [comment]
Tumajarbisaun

**Comment by Lamby777** [comment]
> Tumajarbisaun

Wifenlooof

**Comment by Lamby777** [comment]
ohhhhhh right i should prob do the whole page thing too, almost forgot about that

**Comment by Lamby777** [comment]
oop almost forgot the paginate list part

**Comment by IIIzP0III** [comment]
completed
