### ISSUE TITLE
Warn/confirm on home overwrite

### ISSUE THREAD

**Issue by Lamby777** [IIIzP0III/Back-at-Home#7]
Currently, `/sethome` overwrites existing homes without any warning or confirmation prompt... And there's no way to recover those homes.

Could get annoying for "quick homes" like if you have something like `/sethome brb` for when you need to go somewhere real quick and come back... Maybe a separate command to skip the confirmation? `/sethomew`? Or maybe `/newhome` would refuse to overwrite old homes while `/sethome` does what it currently does. That seems like the best solution imo

**Comment by Lamby777** [comment]
@IIIzP0III

**Comment by IIIzP0III** [comment]
making it into two commands /sethome & /newhome would solve the issue I had with it -
by having the option without a confirmation prompt -
good thinking
